import XCTest

@testable import AdventOfCode

final class Day08Tests: XCTestCase {
  // Smoke test data provided in the challenge question

  let testData = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """
  

  func testPart1() throws {
    let challenge = Day08(data: testData)
    XCTAssertEqual(String(describing: challenge.part1()), "14")
  }

  func testPart2() throws {
    let challenge = Day08(data: testData)
    XCTAssertEqual(String(describing: challenge.part2()), "34")
  }
}

